-- MySQL Script generated by MySQL Workbench
-- Tue Jan 27 17:00:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema copa_do_mundo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `copa_do_mundo` ;

-- -----------------------------------------------------
-- Schema copa_do_mundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `copa_do_mundo` DEFAULT CHARACTER SET utf8 ;
USE `copa_do_mundo` ;

-- -----------------------------------------------------
-- Table `copa_do_mundo`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_do_mundo`.`grupos` ;

CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`grupos` (
  `id_grupos` INT NOT NULL AUTO_INCREMENT,
  `nome` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_grupos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`selecoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_do_mundo`.`selecoes` ;

CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`selecoes` (
  `id_selecoes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `qtd_copa_vencida` INT NOT NULL DEFAULT 0,
  `grupos_id_grupos` INT NOT NULL,
  PRIMARY KEY (`id_selecoes`),
  INDEX `fk_selecoes_grupos1_idx` (`grupos_id_grupos` ASC) VISIBLE,
  CONSTRAINT `fk_selecoes_grupos1`
    FOREIGN KEY (`grupos_id_grupos`)
    REFERENCES `copa_do_mundo`.`grupos` (`id_grupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`estadios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_do_mundo`.`estadios` ;

CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`estadios` (
  `id_estadios` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(200) NULL,
  `pais` VARCHAR(200) NULL,
  `capacidade` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_estadios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`partidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_do_mundo`.`partidas` ;

CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`partidas` (
  `id_partidas` INT NOT NULL AUTO_INCREMENT,
  `id_selecoes` INT NOT NULL,
  `id_selecoes1` INT NOT NULL,
  `id_estadios` INT NOT NULL,
  `gols_selecao_a` INT NOT NULL DEFAULT 0,
  `gols_selecao_b` INT NOT NULL DEFAULT 0,
  `horario` DATETIME NOT NULL,
  `bilheteria` FLOAT NOT NULL,
  PRIMARY KEY (`id_partidas`),
  INDEX `fk_partidas_selecoes1_idx` (`id_selecoes` ASC) VISIBLE,
  INDEX `fk_partidas_selecoes2_idx` (`id_selecoes1` ASC) VISIBLE,
  INDEX `fk_partidas_estadios1_idx` (`id_estadios` ASC) VISIBLE,
  CONSTRAINT `fk_partidas_selecoes1`
    FOREIGN KEY (`id_selecoes`)
    REFERENCES `copa_do_mundo`.`selecoes` (`id_selecoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_selecoes2`
    FOREIGN KEY (`id_selecoes1`)
    REFERENCES `copa_do_mundo`.`selecoes` (`id_selecoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_estadios1`
    FOREIGN KEY (`id_estadios`)
    REFERENCES `copa_do_mundo`.`estadios` (`id_estadios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`jogadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_do_mundo`.`jogadores` ;

CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`jogadores` (
  `id_jogador` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `n_camisa` INT NOT NULL,
  `n_gols` INT NULL DEFAULT 0,
  `n_cartao_amarelo` INT NULL DEFAULT 0,
  `n_cartao_vermelho` INT NULL DEFAULT 0,
  `faltas_sofrida` INT NULL DEFAULT 0,
  `faltas_cometidas` INT NULL DEFAULT 0,
  `id_selecoes` INT NOT NULL,
  PRIMARY KEY (`id_jogador`),
  INDEX `fk_jogadores_selecoes_idx` (`id_selecoes` ASC) VISIBLE,
  CONSTRAINT `fk_jogadores_selecoes`
    FOREIGN KEY (`id_selecoes`)
    REFERENCES `copa_do_mundo`.`selecoes` (`id_selecoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`jogadores_has_partidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_do_mundo`.`jogadores_has_partidas` ;

CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`jogadores_has_partidas` (
  `id_jogador` INT NOT NULL,
  `id_partidas` INT NOT NULL,
  PRIMARY KEY (`id_jogador`, `id_partidas`),
  INDEX `fk_jogadores_has_partidas_partidas1_idx` (`id_partidas` ASC) VISIBLE,
  INDEX `fk_jogadores_has_partidas_jogadores1_idx` (`id_jogador` ASC) VISIBLE,
  CONSTRAINT `fk_jogadores_has_partidas_jogadores1`
    FOREIGN KEY (`id_jogador`)
    REFERENCES `copa_do_mundo`.`jogadores` (`id_jogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogadores_has_partidas_partidas1`
    FOREIGN KEY (`id_partidas`)
    REFERENCES `copa_do_mundo`.`partidas` (`id_partidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
